name: 'move-tags'
description: 'Moving tag'
author: 'snsina'
inputs:
  tag_name:
    required: true
  commit_sha:
    required: true
outputs:
  cache-hit:
    description: 'A boolean value to indicate an exact match was found for the primary key'
runs:
  using: "composite"
  steps:
    - run: |
        set -e
        git pull origin
        ls
        git tag -f ${{ github.event.inputs.tag_name }} ${{ github.event.inputs.commit_sha }}
        git push origin -f ${{ github.event.inputs.tag_name }}
        ls
      shell: bash
